# Generated by Django 5.2.4 on 2025-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_MIND', 'Change Mind'), ('FOUND_CHEAPER', 'Found Cheaper'), ('TOO_LONG_DELIVERY', 'Too Long Delivery'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
