# Generated by Django 5.2.4 on 2025-08-21 09:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount discounted by coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount after discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_MIND', 'Change Mind'), ('FOUND_CHEAPER', 'Found Cheaper'), ('WRONG_ORDER', 'Wrong Order'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Coupon code entered by the user', max_length=255, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_discount_amount', models.DecimalField(decimal_places=2, help_text='Maximum discount amount', max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date of the coupon', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, default=1, help_text='Number of times the coupon can be used (NULL = unlimited)', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
            ],
            options={
                'db_table': 'coupons',
                'indexes': [models.Index(fields=['code'], name='idx_coupons_code'), models.Index(fields=['expires_at'], name='idx_coupons_expires_at')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['coupon'], name='idx_orders_coupon_id'),
        ),
    ]
