# Generated by Django 5.2.4 on 2025-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_coupon_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('OUT_OF_STOCK', 'Out Of Stock'), ('SUSPICIOUS_ORDER', 'Suspicious Order'), ('PAYMENT_ISSUE', 'Payment Issue'), ('ADDRESS_ISSUE', 'Address Issue'), ('OTHER', 'Other')], help_text='Reason for rejection by admin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_MIND', 'Change Mind'), ('FOUND_CHEAPER', 'Found Cheaper'), ('WRONG_ORDER', 'Wrong Order'), ('OTHER', 'Other')], help_text='Reason for cancellation by customer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255),
        ),
    ]
