# Generated by Django 5.2.4 on 2025-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_reject_reason_alter_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for guest orders', max_length=255, null=True),
        ),
    ]
