# Generated by Django 5.2.4 on 2025-08-27 06:30
from __future__ import annotations

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url_product_image_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'rating',
                    models.PositiveSmallIntegerField(
                        help_text='Rating from 1 to 5 stars',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='Optional review title',
                        max_length=255,
                    ),
                ),
                (
                    'comment',
                    models.TextField(
                        blank=True, help_text='Optional review comment',
                    ),
                ),
                (
                    'is_verified_purchase',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this review is from a verified purchase',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='products.product',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_reviews',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'product_reviews',
                'indexes': [
                    models.Index(
                        fields=['product'],
                        name='idx_reviews_product_id',
                    ),
                    models.Index(fields=['user'], name='idx_reviews_user_id'),
                    models.Index(fields=['rating'], name='idx_reviews_rating'),
                    models.Index(
                        fields=['created_at'],
                        name='idx_reviews_created_at',
                    ),
                ],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
